# PyTorch functions for mathematical operations

### Five mathematical functions of PyTorch

PyTorch is an open-source machine learning framework written in Python, C++, and CUDA, being used for applications such as computer vision, natural language processing, neural networks, and convolutional neural networks, being these last two part of the deep learning field, it is not a secret that it requires a lot of mathematical concepts, here are some of them.
- `torch.add(input, other, *, alpha=1, out=None)`
- `torch.eq(input, other, out=None) → Tensor`
- function 3
- function 4
- function 5

In [2]:
import torch

# Function 1 -  `torch.add(input, other, *, alpha=1, out=None)`

Takes an entry tensor(`other`) and multiply each element by the scalar(`alpha`) and added to each element of the first entry tensor(`input`), the results are shown on screen or it is possible to store it into another tensor that is not required(`out`). 

Parameters:
- `input`(Tensor): The first input tensor.
- `other`(Tensor): The second input tensor.
- `alpha`(Number): The scalar multiplier of other.

Keyword Arguments:
- `out`(Tensor, optional):

The shapes of input and other must be broadcastable, two tensors are “broadcastable” if the following rules hold:
- Each tensor has at least one dimension.
- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

### out = input Each tensor has at least one dimension.+ alpha × other


In [2]:
# Example 1 - working
t1 = torch.randn(4, 4)
print(t1)#t1 tensor before the operation
print(t1.shape)#Shape of the t1 tensor
t2 = torch.randn(4, 4)
t1 = torch.add(t1, t2, alpha=1)
t1 #t1 after the operation

tensor([[-2.3983e+00, -5.7795e-01, -2.6534e-01,  2.0648e-03],
        [-4.1110e-01, -1.4163e-01, -1.7890e-01,  5.8431e-01],
        [-1.3411e-01, -6.2748e-02, -1.7479e+00, -8.7839e-02],
        [ 2.0938e-01,  2.7207e-01, -1.0960e+00,  2.2501e+00]])
torch.Size([4, 4])


tensor([[-1.1131, -1.0568, -0.0180,  0.6416],
        [-1.0150, -0.5259,  0.3634,  1.0278],
        [-0.5456,  0.8926, -3.0427, -1.5103],
        [-0.2070, -0.3087, -2.6269,  2.5873]])

For the input (`t1`) we create a random tensor with the shape [4, 4] (4 rows and 4 columns) and another random tensor (`t2`) with the same shape, where `t1=input` and `t2=other` and `alpha=1`, the output is stored in t1, so in this case, it wasn't necessary the `out` parameter.

In [3]:
# Example 2 - working
t1 = torch.randn(5, 4) #t1 with the shape of [5, 4]
t1
t2 = torch.randn(5, 1) #t2 with the shape of [5, 1]
t3 = torch.zeros(t1.shape) #Create a tensor full of zeros
print('\n\nt3 before the operation')
print(t3)
torch.add(t1, t2, alpha=0.5, out=t3)
print('\nt3 after the operation')
t3



t3 before the operation
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

t3 after the operation


tensor([[-1.4679, -0.5264,  0.6546, -0.7147],
        [-0.7428, -0.3969, -0.5442, -0.3227],
        [ 1.0042, -1.2107, -0.0159,  0.3856],
        [ 0.6697, -1.2800, -0.9486, -1.0828],
        [-2.2538,  0.3640,  1.4401, -1.2075]])

Similarly to the first example, but in this one we take the optional parameter as t3, first, we create a tensor of the shape of the `input` parameter with the function `zeros()`, what this function does is fill the tensor with zeros (as the function say) and we use it as the output of the add function, our result are now in `t3` tensor for future usages.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.randn(6, 3) #t1 with the shape of [6, 3]
t2 = torch.empty((0,))
t1 = torch.add(t1, t2, alpha=1)

This one throws a `RuntimeError` because the tensors `t1=input` and `t2=other` are not broadcastable.

Usage of this function: Whenever we need to multiply one tensor to a scalar and then add it to another tensor.

## Function 2 -  torch.eq(input, other, out=None) → Tensor

Takes an (`input`) tensor and computes element-wise equality with another tensor or a float (`other`), the output is stored in another tensor (`out`), this last one is optional. It returns a tensor of type `torch.BoolTensor` containing a True at each location where comparision is true.

Parameters:
- `input`(Tensor): The first input tensor.
- `other`(Tensor or float): The second input tensor.
- `output`(Tensor, optional): Must be a ByteTensor.


In [44]:
# Example 1 - working
t1 = torch.randn(4, 4)
print(t1) 
torch.eq(t1, t1[0, 0]) #We choose the first element.

tensor([[ 0.4800,  0.0702, -1.1560,  0.6417],
        [ 0.6001,  1.4824, -0.6597, -0.1528],
        [ 2.0620,  0.7150, -0.6709, -1.5106],
        [ 0.7725,  0.1399, -0.7556, -0.8114]])


tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In this example we generate a random tensor [4, 4] and we choose an element from the tensor (`t1[0, 0]`) to see how the function works and as it was expected, in the output we can verify that only the first element is `True`, if there was another element equal to the first one, that position would be also `True`.

In [64]:
# Example 2 - working
t1 = torch.randn(4, 4)
t2 = torch.tensor([
    [t1[0, 0], t1[0, 1], t1[0, 2], 4.5],
    [t1[1, 0], t1[1, 1], t1[1, 2], 4.2],
    [t1[2, 0], t1[2, 1], t1[2, 2], 4.1],
    [t1[3, 0], t1[3, 1], t1[3, 2], 2.3]
])
t3 = torch.zeros(t1.shape).byte()
print(t1)
print(t2)
print(t3) #t3 before the operation
torch.eq(t1, t2, out=t3)
t3

tensor([[ 0.8996, -0.6768,  0.4861,  0.6727],
        [ 0.8248, -0.4119, -0.2530, -2.5720],
        [ 1.2162,  0.5141, -1.5502,  0.3786],
        [ 0.6648,  1.5367,  0.4531,  0.5004]])
tensor([[ 0.8996, -0.6768,  0.4861,  4.5000],
        [ 0.8248, -0.4119, -0.2530,  4.2000],
        [ 1.2162,  0.5141, -1.5502,  4.1000],
        [ 0.6648,  1.5367,  0.4531,  2.3000]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)


tensor([[1, 1, 1, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 0]], dtype=torch.uint8)

Here we do some minor changes, we accept the `other` tensor and not just a scalar. The `other` tensor is just the `t1` tensor but the last column was filled with random values, we store the output in `t3`, and by the way, `t3` must be `ByteTensor` type, otherwise, it would crash, we're going to take a look at it in the next example.

In [68]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.randn(4, 4)
t2 = torch.tensor([
    [t1[0, 0], t1[0, 1], t1[0, 2], 4.5],
    [t1[1, 0], t1[1, 1], t1[1, 2], 4.2],
    [t1[2, 0], t1[2, 1], t1[2, 2], 4.1],
    ])
t3 = torch.zeros(t1.shape)
print(t1)
print(t2)
print(t3) #t3 before the operation
torch.eq(t1, t2, out=t3)
t3

tensor([[-0.3272,  0.9572, -0.4800, -0.2697],
        [ 0.2911,  0.2076, -1.5899,  0.6957],
        [-1.3415, -0.0879,  0.2303,  1.0783],
        [-1.4973,  0.8555, -0.3038, -0.0487]])
tensor([[-0.3272,  0.9572, -0.4800,  4.5000],
        [ 0.2911,  0.2076, -1.5899,  4.2000],
        [-1.3415, -0.0879,  0.2303,  4.1000]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

This is the same last example, but the `t2` tensor now has three rows instead of 4 rows and it lead to a crash, now we know that the `input` tensor and the `other` tensor must have the same size.

This function is great when it comes to makes comparission between tensors, or if we just want to know an element-wise comparision with a `float`, the great thing about comparissions in PyTorch is that it receives the same parameter for the other types, these are the others.
- `torch.ge(input, other, out=None) → Tensor` computes `input` >= `other` element-wise.
- `torch.gt(input, other, out=None) → Tensor` computes `input` > `other` element-wise.
- `torch.le(input, other, out=None) → Tensor` computes `input` <= `other` element-wise.
- `torch.lt(input, other, out=None) → Tensor` computes `input` < `other` element-wise

## Function 3 - ???

Add some explanations

In [8]:
# Example 1 - working

Explanation about example

In [9]:
# Example 2 - working

Explanation about example

In [10]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 4 - ???

Add some explanations

In [11]:
# Example 1 - working

Explanation about example

In [12]:
# Example 2 - working

Explanation about example

In [13]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 5 - ???

Add some explanations

In [14]:
# Example 1 - working

Explanation about example

In [15]:
# Example 2 - working

Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit()